# SPDX-License-Identifier: MIT
---
# tasks/linux.yml file for configure_updates

# Copies all of the utilities under this role's files/*.sh path to /usr/local/bin/ on the target node
- name: "Install utility scripts"
  ansible.builtin.copy:
    remote_src: false
    src: "{{ item }}"
    dest: /usr/local/bin
    owner: 'root'
    group: 'root'
    mode: '0755'
  with_fileglob:
    - "*.sh"
  become: true
  become_method: ansible.builtin.sudo

# Gather facts to determine ansible_service_mgr
- name: Gather system facts
  ansible.builtin.gather_facts:

# Uses systemd if present, by default
- name: Include systemd tasks
  ansible.builtin.include_tasks: linux-systemd.yml
  when: ansible_service_mgr == 'systemd'

# Cron is a fallback if systemd is not present
- name: Include cron tasks
  ansible.builtin.include_tasks: linux-cron.yml
  when: ansible_service_mgr != 'systemd'
